# Generated by Django 4.2 on 2023-08-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='User',
            new_name='user',
        ),
    ]
