# Generated by Django 4.2 on 2023-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp1', '0002_rename_user_employeedetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='empcode',
            field=models.CharField(max_length=50),
        ),
    ]
