# Generated by Django 4.2 on 2023-08-13 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empapp1', '0003_alter_employeedetail_empcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1_name', models.CharField(max_length=50)),
                ('company1_desig', models.CharField(max_length=50, null=True)),
                ('company1_duration', models.CharField(max_length=50, null=True)),
                ('company1_salary', models.CharField(max_length=60, null=True)),
                ('company2_name', models.CharField(max_length=50)),
                ('company2_desig', models.CharField(max_length=50, null=True)),
                ('company2_duration', models.CharField(max_length=50, null=True)),
                ('company2_salary', models.CharField(max_length=60, null=True)),
                ('company3_name', models.CharField(max_length=50)),
                ('company3_desig', models.CharField(max_length=50, null=True)),
                ('company3_duration', models.CharField(max_length=50, null=True)),
                ('company3_salary', models.CharField(max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pg', models.CharField(max_length=200)),
                ('clg_name_pg', models.CharField(max_length=200, null=True)),
                ('year_of_passing_pg', models.CharField(max_length=50, null=True)),
                ('persentage_pg', models.CharField(max_length=60, null=True)),
                ('course_g', models.CharField(max_length=200)),
                ('clg_name_g', models.CharField(max_length=200, null=True)),
                ('year_of_passing_g', models.CharField(max_length=50, null=True)),
                ('persentage_g', models.CharField(max_length=60, null=True)),
                ('course_ssc', models.CharField(max_length=200)),
                ('school_name_ssc', models.CharField(max_length=200, null=True)),
                ('year_of_passing_ssc', models.CharField(max_length=50, null=True)),
                ('persentage_ssc', models.CharField(max_length=60, null=True)),
                ('course_hsc', models.CharField(max_length=200)),
                ('school_name_hsc', models.CharField(max_length=200, null=True)),
                ('year_of_passing_hsc', models.CharField(max_length=50, null=True)),
                ('persentage_hsc', models.CharField(max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
